site_name: Automated City Mapping and Car Driving
theme:
  name: material
  palette:
    scheme: slate
  features:
    toc.integrate

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list

nav:
  - Home: index.md
  - Clustering: clustering.md
  - Environment: environment.md
  - Agent: car.md
  - API: api.md

